# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'openid_connect'
gem 'aws-sdk-iam', '~> 1.3'
gem 'aws-sdk-ec2', '~> 1'
gem 'tzinfo-data'
gem 'slack-notifier'

group :development do
  gem "pry-byebug"
end
